### PR TITLE
Restructure tad/tools folder with requirements and research

### PR DESCRIPTION
**Pull request by uittenbroekrobbert**
# Description

Please include a summary of the changes and the related issue.

### CODE REVIEW

**Comment by anneschuth** [comment]
Good idea, but maybe also change the title of these pages?
image

**Comment by laurensWe** [comment]
This will get some merge conflicts with this one, https://github.com/MinBZK/ai-validation/pull/91 what do you think of my structure there?

**Review by anneschuth — APPROVED** [review]

**Comment by anneschuth** [comment]
@laurensWe maybe merge yours first, we may not need this PR

**Comment by anneschuth** [comment]
One more, sorry, maybe we should rename the directory "Tools" to "Existing Tools"?

**Comment by laurensWe** [comment]
This looks good, but could you first rebase @uittenbroekrobbert ?

**Review by berrydenhartog — APPROVED** [review]
LGTM

**Review by laurensWe — APPROVED** [review]
LGTM

**Pull request merged**
