### PR TITLE
Add Instrument Registry to our product graph

### PR DESCRIPTION
**Pull request by anneschuth**
# Description

Add Instrument Registry to our product graph:
image

### CODE REVIEW

**Review by berrydenhartog — APPROVED** [review]
LGTM but title is a bit confusing. Seems like you only changes tmt to amt

**Comment by anneschuth** [comment]
The only thing I did was add adding the registry, renaming the variables has no external effect (their naming was just confusing to me).

**Comment by laurensWe** [comment]
Renaming will conflict with https://github.com/MinBZK/ai-validation/pull/174 but i will fix this. Also I think what Berry says, he is onto something because i don't see the change though, the picture you post here is good but i don't see any changes in the code

**Comment by anneschuth** [comment]
I've added this line:
https://github.com/MinBZK/ai-validation/pull/177/files#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R21

**Comment by laurensWe** [comment]
> I've added this line: https://github.com/MinBZK/ai-validation/pull/177/files#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R21

Ah you are correct, my apologies, then LGTM :)

**Review by laurensWe — APPROVED** [review]

**Pull request merged**
